version: "1.0"

services:

  # Backend API
  backend-api:
    image: raouamth/backend-mysql-session16
    container_name: backend-api
      - PORT=3001   
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    env_file:
      - .env
      




  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:


